fix build failures with gcc-14
The builds on riscv64,ppc64el and s390x are failing with the error:

odbc.c: In function '_odbc_fix_literals.isra':
odbc.c:1998:35: error: 'quote_char' may be used uninitialized [-Werror=maybe-uninitialized]
 1998 |                 } else if (quoted && *s==quote_char) {
      |                            ~~~~~~~^~~~~~~~~~~~~~~~~
odbc.c:1990:14: note: 'quote_char' was declared here
 1990 |         char quote_char;
      |              ^~~~~~~~~~

The builds on armhf (32 bit system) is failing with the error:

In file included from /usr/include/stdio.h:970,
                 from mdb-sql.c:19:
In function ‘fgets’,
    inlined from ‘main’ at mdb-sql.c:423:9:
/usr/include/arm-linux-gnueabihf/bits/stdio2.h:313:12: error: argument 2 value -1 is negative [-Werror=stringop-overflow=]
  313 |     return __fgets_alias (__s, __n, __stream);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/features.h:510,
                 from /usr/include/arm-linux-gnueabihf/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:28:
/usr/include/arm-linux-gnueabihf/bits/stdio2-decl.h: In function ‘main’:
/usr/include/arm-linux-gnueabihf/bits/stdio2-decl.h:96:14: note: in a call to function ‘__fgets_alias’ declared with attribute ‘access (write_only, 1, 2)’
   96 | extern char *__REDIRECT (__fgets_alias,
      |              ^~~~~~~~~~

which is caused by overflowing because of the difference in size of 'unsigned int'.

Signed-off-by: Sudip Mukherjee <sudipm.mukherjee@gmail.com>